["pyproject.toml".tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pytest-cov = "^3.0.0"
pytest-xdist = {extras = ["psutil"], version = "^2.1.0"}
pytest-sugar = "^0.9.4"
Faker = "^9.5.0"
pytest-snapshot = "^0.8.0"
